FROM quay.io/shahlab_singularity/singularity_base:v0.0.1

ADD . /app

RUN rm -rf /opt/conda/lib/python3.7/site-packages/pypeliner*
RUN pip install -r /app/requirements.txt


RUN conda create --name museq python=2.7
# activate env
SHELL ["conda", "run", "-n", "museq", "/bin/bash", "-c"]
RUN conda install -c conda-forge -c shahcompbio museq intervaltree museqportrait==0.99.13 -y
# deactivate env
SHELL ["conda", "run", "-n", "base", "/bin/bash", "-c"]
# add env to path
ENV PATH="${PATH}:/opt/conda/envs/museq/bin"


# Install basic packages
RUN apt-get update && apt-get install -y libltdl7 && rm -rf /var/lib/apt/lists/*
RUN conda update -y conda
RUN conda install -c bioconda vcftools tabix bcftools snpeff
RUN conda install -c bioconda perl-vcftools-vcf==0.1.15

# TODO: this might have to go in another env
RUN conda install -c aroth85 strelka==1.0.14

RUN conda install -c conda-forge intervaltree


# mutationseq - https://github.com/shahcompbio/singularity_containers/blob/master/wgs_somatic/dockerfile line 13-15, 24
# vcf tools - https://github.com/shahcompbio/singlecellpipeline_docker_containers/blob/master/dockerfiles/vcftools/
# strelka - https://github.com/shahcompbio/singlecellpipeline_docker_containers/blob/master/dockerfiles/strelka/dockerfile
