FROM quay.io/shahlab_singularity/singularity_base:v0.0.1
FROM scdnaprod.azurecr.io/singlecellpipeline/python_singlecell_qc:v0.1.2

ADD . /app

# Install any needed packages specified in requirements.txt
RUN conda install -c dranew remixt && rm -rf /opt/conda/lib/python2.7/site-packages/remixt*
RUN apt-get update && apt-get install libc-dev libz-dev -y && apt-get install build-essential -y && rm -rf /var/lib/apt/lists/* && conda install -c bioconda cython
RUN pip install git+https://github.com/amcpherson/remixt.git@v0.5.13
RUN mkdir -p /root/.config/matplotlib && echo "backend : Agg" > /root/.config/matplotlib/matplotlibrc

RUN rm -rf /opt/conda/lib/python3.7/site-packages/pypeliner*
RUN pip install -r /app/requirements.txt

# Make port 80 available to the world outside this container
EXPOSE 80

# Define environment variable
ENV NAME remixt

# Run app.py when the container launches
CMD ["remixt"]
