FROM quay.io/wgspipeline/singularity_base:v0.0.1

ADD . /app

RUN  pip install -r /app/requirements.txt
RUN conda install -c bioconda -c conda-forge samtools cryptography
RUN conda install -c bioconda -c conda-forge bcftools cryptography
RUN conda install -c bioconda freebayes
RUN conda install -c shahcompbio -c bioconda vcf2maf_shahcompbio
RUN  mkdir /usr/share/man/man1/ && apt-get update && apt-get install -y libltdl7 parallel default-jdk && rm -rf /var/lib/apt/lists/*
RUN cp -r /app/rtg/* /opt/conda/bin/
RUN conda install -c bioconda vcftools tabix bcftools snpeff
RUN conda install -c bioconda perl-vcftools-vcf==0.1.15

RUN conda create --name museq python=2.7
SHELL ["conda", "run", "-n", "museq", "/bin/bash", "-c"]
RUN conda install -c conda-forge -c shahcompbio museq intervaltree museqportrait==0.99.13 -y
ENV PATH="${PATH}:/opt/conda/envs/museq/bin"
