FROM quay.io/wgspipeline/singularity_base:v0.0.1

ADD . /app

RUN apt-get update && apt install build-essential gcc libfontconfig1 -y && rm -rf /var/lib/apt/lists/*

RUN rm -rf /opt/conda/lib/python3.7/site-packages/pypeliner*
RUN pip install -r /app/requirements.txt

RUN conda install -c bioconda bwa
RUN conda install -c bioconda -c conda-forge samtools cryptography
RUN conda install -c conda-forge freetype -y
RUN conda install -c bioconda fastqc
RUN conda install -c bioconda picard
#RUN conda install -c r r=3.6.1 r-plyr r-getopt

RUN conda create --name igvtools
SHELL ["conda", "run", "-n", "igvtools", "/bin/bash", "-c"]
RUN conda install -c bioconda -c conda-forge igvtools openjdk=11.0.8


RUN conda create --name picard
SHELL ["conda", "run", "-n", "picard", "/bin/bash", "-c"]
RUN conda install --file /app/picard_reqs.txt

ENV PATH="/opt/conda/envs/igvtools/bin:/opt/conda/envs/picard/bin:$PATH"
