FROM quay.io/wgspipeline/singularity_base:v0.0.1

ADD . /app

RUN apt-get update && apt install build-essential gcc -y && rm -rf /var/lib/apt/lists/*
RUN conda install -c bioconda -c dranew destruct==0.4.18 destruct_utils==0.4.18
RUN rm -rf /opt/conda/lib/python3.7/site-packages/destruct* &&  pip install git+https://github.com/amcpherson/destruct.git@master
RUN pip install -e git+https://github.com/amcpherson/blossomv.git#egg=blossomv
RUN pip install networkx==2.1
RUN cp /app/filter_annotate_breakpoints.py /opt/conda/bin && chmod 777 /opt/conda/bin/filter_annotate_breakpoints.py

RUN conda install -c bioconda svaba


RUN rm -rf /opt/conda/lib/python3.7/site-packages/pypeliner*
RUN pip install -r /app/requirements.txt
RUN conda install -c bioconda -c conda-forge samtools cryptography



RUN conda create --name lumpy python=2.7
SHELL ["conda", "run", "-n", "lumpy", "/bin/bash", "-c"]
RUN conda install -c componc -c bioconda  lumpy-sv=0.2.12
RUN conda install -c bioconda sambamba
RUN echo "aliasawk=gawk" >> ~/.bashrc
RUN cp /app/lumpy_extractSplitReads_BwaMem  /opt/conda/envs/lumpy/bin/lumpy_extractSplitReads_BwaMem

ENV PATH="${PATH}:/opt/conda/envs/lumpy/bin"
